[FEAT] Footer 구현 (#5)
Hongmoon-gak/Job1-Web pull request #6
Opened 2023-07-19 17:07 UTC by jh2ee

## 관련 이슈
🔒 Closes  

(#5)

## 작업내용

- [x] 작업 내용
- [ ] Footer 구현

|작업 전|작업 후|
|:---:|:---:|
|<img width="250" src="">|<img width="1439" alt="image" src="https://github.com/Hongmoon-gak/Job1-Web/assets/121475533/8d1173ce-fda3-4ee3-a998-f26e602fea8b">|

## 추후 진행할 사항
반응형? 수정할 사항 없어보임

## 리뷰포인트

footer 높이 적당한지 봐주세요

## Reference

## Checklist
- [ ] 필요없는 주석, 프린트문 제거했는지 확인
- [ ] 컨벤션 지켰는지 확인

2023-07-20 02:21 UTC, ju1e3718 commented
p5; 수고많으셨습니다~!

2023-07-20 10:09 UTC, lenamin requested changes
고생많으셨어요 :)

2023-07-20 10:09 UTC, lenamin commented on job1/src/App.js
>  }
p1; 
이 파일에서 컨플릭 나는 부분 머지 전에 해결 부탁드립니다!

2023-07-20 11:32 UTC, hye-inA commented
p5; 고생하셨습니다!

2023-07-21 02:58 UTC, jh2ee commented on job1/src/App.js
>  }
확인했습니다

2023-07-21 06:11 UTC, merged